### ISSUE TITLE
Ngrok does not work over network

### ISSUE THREAD

**Issue by anonymh** [microsoftgraph/nodejs-webhooks-sample#351]
So I have a problem with ngrok. I'v worked with nexphisher and blackeye. And it worked only on devices that are connected to the same network as me. I"m using kali linux on oracle VM Ubunto(last Version). Can anyone help?

**Comment by jasonjoh** [comment]
I'm sorry but I'm not sure how I can help. The [ngrok docs](https://ngrok.com/docs) have an **Ask a question** button on the page that emails their support team.
