### ISSUE TITLE
Tutorial doesn't directly reference this repo

### ISSUE THREAD

**Issue by daverickdunn** [microsoftgraph/nodejs-webhooks-sample#471]
Just an FYI, [this page](https://learn.microsoft.com/en-us/samples/microsoftgraph/nodejs-webhooks-sample/microsoft-graph-webhooks-sample-for-nodejs/) references one of the env files within this repo, but doesn't actually link to the repo directly, had to re-read the thing a couple of times when all I want is to grab the code and go.

**Comment by jasonjoh** [comment]
Sorry for the delay in responding here, somehow I missed the notification on this one. The only reference I see on that page does link directly to the sample.env file. I'm not sure if I'm missing another reference you're referring to?

![image](https://github.com/microsoftgraph/nodejs-webhooks-sample/assets/8966342/9d6d7818-5362-42d4-8a8f-abff0267fbe9)

There's also a link to the repo at the top of the page, a button labeled "Browse code". Please let me know if this doesn't address your concern.
